name: ModeratorMode
author: RoboMWM
version: '${project.version}-${git.commit.id.abbrev}'
main: com.robomwm.moderatormode.ModeratorMode
api-version: '1.15'

commands:
  moderatormode:
    description: Toggles moderator mode
    usage: /moderatormode
    permission: moderatormode.toggle

permissions:
  moderatormode.toggle:
    description: Permission to toggle /moderatormode
    default: op